package common

// LogField ...
type LogField string

var (
	// LogFieldModule ...
	LogFieldModule = "module"
	// LogFieldWidget ...
	LogFieldWidget = "widget"
	// LogFieldView ...
	LogFieldView = "view"
	// LogFieldMethod ...
	LogFieldMethod = "method"
	// LogFieldEngine ...
	LogFieldEngine = "method"
)
